# Traefik Static Configuration
# This file contains the main Traefik configuration including providers, entrypoints, and SSL settings

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and Dashboard configuration
api:
  dashboard: true
  debug: false
  insecure: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        options: default
        certResolver: letsencrypt
  traefik:
    address: ":8080"

# Providers configuration
providers:
  # Docker provider for automatic service discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
    watch: true
    swarmMode: false
    useBindPortIP: false
    
  # File provider for dynamic configuration
  file:
    directory: /etc/traefik/dynamic
    watch: true

# Certificate resolvers for Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: "${ACME_EMAIL}"
      storage: /letsencrypt/acme.json
      keyType: EC256
      # Use HTTP challenge for certificate validation
      httpChallenge:
        entryPoint: web
      # Uncomment for DNS challenge if needed (requires DNS provider configuration)
      # dnsChallenge:
      #   provider: cloudflare
      #   delayBeforeCheck: 30s
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"

# Logging configuration
log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

# Access logs
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
    retryAttempts: true
    minDuration: "10ms"

# Metrics configuration for Prometheus
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Ping endpoint for health checks
ping:
  entryPoint: traefik

# Tracing (optional, can be enabled for debugging)
# tracing:
#   jaeger:
#     samplingServerURL: http://jaeger:14268/api/sampling
#     localAgentHostPort: jaeger:6831

# Pilot configuration (disabled)
pilot:
  dashboard: false